In [25]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import display, clear_output

In [26]:

def fillDiagonal(board):
    def generateDiagonal():
        arr=np.arange(1,10)
        for i in range(3):
            np.random.shuffle(arr)
            yield arr.reshape((3,3))

    out=generateDiagonal()
    board[:3,:3]=next(out)
    board[3:6,3:6]=next(out)
    board[6:,6:]=next(out)
    return(board)


In [27]:
def isValid(num,row,col,board):

        #row check
        rowCheck = num in board[row,:]

        #column check
        columnCheck = num in board[:,col]

        #subgrid check
        subgridCheck = num in board[3*(row//3):3*((row//3)+1),3*(col//3):3*((col//3)+1)]

        if rowCheck or columnCheck or subgridCheck:
            return False
        return True

def emptyCell(board):
        for i in range(9):
            for j in range(9):
                if board[i,j]==0:
                    return i,j
                
        return None

def solve(board):
    location=emptyCell(board)
    if not location:
        return True
    row,col=location

    count=0
    for num in range(1,10):
        if(isValid(num,row,col,board)):
            board[row,col]=num
            if solve(board):
                return True
            else:
                board[row,col]=0

    return False

def countSolve(board,count):
    location=emptyCell(board)
    if not location:
        count[0]+=1
        return
    row,col=location
    for num in range(1,10):
        if(isValid(num,row,col,board)):
            board[row,col]=num
            if countSolve(board,count):
                return True
            else:
                board[row,col]=0
    
      


In [28]:
board = np.zeros((9,9),dtype=int)
while(not solve(fillDiagonal(board))):
    pass
print(board)


[[1 4 9 2 5 3 6 8 7]
 [8 6 3 1 4 7 5 2 9]
 [7 2 5 6 9 8 3 4 1]
 [2 5 1 7 3 4 9 6 8]
 [3 8 4 9 1 6 7 5 2]
 [6 9 7 5 8 2 4 1 3]
 [5 7 6 8 2 9 1 3 4]
 [9 3 8 4 6 1 2 7 5]
 [4 1 2 3 7 5 8 9 6]]


In [32]:

def generateQuestion(solution,difficulty,count):
    if difficulty == "easy":
        n= np.random.randint(40,46)
    elif difficulty == "medium":
        n = np.random.randint(46,51)
    else:
        n = np.random.randint(51,56)

    question = solution.flatten()
    remove=np.random.choice(question.size,n,replace=False)
    question[remove]=0
    question = question.reshape((9,9))
    print(question)
    countSolve(question.copy(),count)
    return question

while(True):
    count=[0]
    question = generateQuestion(board,"easy",count)
    if count[0]==1:
        print(question)
    



[0 0 0 0 5 0 0 8 7 8 0 3 0 0 7 0 2 9 7 2 0 6 0 8 3 4 0 0 0 1 7 3 0 0 0 8 0
 0 0 0 0 0 7 5 0 6 9 7 0 0 0 0 1 0 5 0 6 0 0 0 0 3 0 9 3 0 4 0 0 2 7 5 0 0
 2 3 0 5 8 9 6]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed