In [5]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import display, clear_output

In [6]:

def fillDiagonal(board):
    def generateDiagonal():
        arr=np.arange(1,10)
        for i in range(3):
            np.random.shuffle(arr)
            yield arr.reshape((3,3))

    out=generateDiagonal()
    board[:3,:3]=next(out)
    board[3:6,3:6]=next(out)
    board[6:,6:]=next(out)
    return(board)


In [14]:
def solve(board):
    def isValid(num,row,col,board):

        #row check
        rowCheck = num in board[row,:]

        #column check
        columnCheck = num in board[:,col]

        #subgrid check
        subgridCheck = num in board[3*(row//3):3*((row//3)+1),3*(col//3):3*((col//3)+1)]

        if rowCheck or columnCheck or subgridCheck:
            return False
        return True 
    
    def emptyCell(board):
        for i in range(9):
            for j in range(9):
                if board[i,j]==0:
                    return i,j
                
        return None

    
    def solveBoard(board):


        location=emptyCell(board)
        if not location:
            return True
        row,col=location

        for num in range(1,10):
            if(isValid(num,row,col,board)):
                board[row,col]=num
                if solveBoard(board):
                    return True
                else:
                    board[row,col]=0

        return False
    
    return solveBoard(board)
      


In [16]:
board = np.zeros((9,9),dtype=int)
while(not solve(fillDiagonal(board))):
    pass
print(board)


[[6 5 9 1 3 2 4 7 8]
 [4 7 1 5 6 8 3 9 2]
 [3 2 8 7 4 9 1 5 6]
 [5 3 6 9 2 1 8 4 7]
 [7 9 4 6 8 5 2 3 1]
 [1 8 2 4 7 3 9 6 5]
 [9 6 3 2 1 7 5 8 4]
 [2 4 5 8 9 6 7 1 3]
 [8 1 7 3 5 4 6 2 9]]


In [ ]:
def 