In [72]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import display, clear_output

In [73]:

def fillDiagonal(board):
    def generateDiagonal():
        arr=np.arange(1,10)
        for i in range(3):
            np.random.shuffle(arr)
            yield arr.reshape((3,3))

    out=generateDiagonal()
    board[:3,:3]=next(out)
    board[3:6,3:6]=next(out)
    board[6:,6:]=next(out)
    return(board)


In [74]:
def isValid(num,row,col,board):

        #row check
        rowCheck = num in board[row,:]

        #column check
        columnCheck = num in board[:,col]

        #subgrid check
        subgridCheck = num in board[3*(row//3):3*((row//3)+1),3*(col//3):3*((col//3)+1)]

        if rowCheck or columnCheck or subgridCheck:
            return False
        return True

def emptyCell(board):
        for i in range(9):
            for j in range(9):
                if board[i,j]==0:
                    return i,j
                
        return None

def solve(board):
    location=emptyCell(board)
    if not location:
        return True
    row,col=location

    count=0
    for num in range(1,10):
        if(isValid(num,row,col,board)):
            board[row,col]=num
            if solve(board):
                return True
            else:
                board[row,col]=0

    return False

def countSolve(board,count):
    location=emptyCell(board)
    if not location:
        count[0]+=1
        return
    row,col=location
    for num in range(1,10):
        if(isValid(num,row,col,board)):
            board[row,col]=num
            if countSolve(board,count):
                return True
            else:
                board[row,col]=0
    
      


In [75]:
board = np.zeros((9,9),dtype=int)
while(not solve(fillDiagonal(board))):
    pass
print(board)


[[7 2 8 3 1 6 5 4 9]
 [5 3 9 2 4 8 6 7 1]
 [1 4 6 5 9 7 2 3 8]
 [2 5 7 1 3 4 8 9 6]
 [6 9 1 8 7 5 3 2 4]
 [4 8 3 6 2 9 7 1 5]
 [9 6 2 7 5 1 4 8 3]
 [3 1 5 4 8 2 9 6 7]
 [8 7 4 9 6 3 1 5 2]]


In [76]:

def generateQuestion(solution,difficulty,count):
    if difficulty == "easy":
        n= np.random.randint(36,39)
    elif difficulty == "medium":
        n = np.random.randint(39,42)
    else:
        n = np.random.randint(42,46)

    question = solution.flatten()
    remove=np.random.choice(question.size,n,replace=False)
    question[remove]=0
    question = question.reshape(solution.shape)
    countSolve(question.copy(),count)
    return question

while(True):
    count=[0]
    question = generateQuestion(board,"easy",count)
    if count[0]==1:
        print(question)
        print(board)
        break
    



[[0 0 8 3 0 6 5 0 0]
 [5 0 9 2 0 0 6 7 1]
 [1 4 6 5 0 0 0 0 8]
 [2 0 0 0 0 0 8 9 0]
 [6 0 1 8 7 0 3 2 0]
 [0 0 3 6 2 9 7 0 5]
 [9 6 2 7 0 1 0 8 3]
 [3 0 0 0 8 0 9 6 0]
 [8 0 0 0 6 3 0 0 0]]
[[7 2 8 3 1 6 5 4 9]
 [5 3 9 2 4 8 6 7 1]
 [1 4 6 5 9 7 2 3 8]
 [2 5 7 1 3 4 8 9 6]
 [6 9 1 8 7 5 3 2 4]
 [4 8 3 6 2 9 7 1 5]
 [9 6 2 7 5 1 4 8 3]
 [3 1 5 4 8 2 9 6 7]
 [8 7 4 9 6 3 1 5 2]]
